# -*- coding: utf-8 -*-
"""assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QLz_HwPlHDonGeOogLe8cy1Q64gRalPt
"""

import pandas as pd
import numpy as np
import random

num_records = 1000
age_groups = ['0–10', '11–18', '19–64', '65+']
diagnoses = ['Depression', 'Anxiety', 'Schizophrenia', 'Depression, Anxiety']
treatments = ['Antidepressants', 'Therapy', 'Behavioral Therapy', 'Antipsychotics', 'No Treatment']
cpt_codes = ['99213', '90834', '99214', '90837', '99212', '99215', '99204', '90839', '99243']

patient_ids = [f"P{str(i).zfill(3)}" for i in range(1, num_records + 1)]
ages = np.random.randint(5, 81, num_records)  # Random ages between 5 and 80
age_groups_assigned = ['0–10' if age <= 10 else '11–18' if age <= 18 else '19–64' if age <= 64 else '65+' for age in ages]
diagnoses_assigned = random.choices(diagnoses, k=num_records)
phq_9_scores = np.random.randint(0, 28, num_records)  # Scores from 0 to 27
treatments_assigned = random.choices(treatments, k=num_records)
cpt_codes_assigned = random.choices(cpt_codes, k=num_records)

data = pd.DataFrame({
    "Patient_ID": patient_ids,
    "Age": ages,
    "Age_Group": age_groups_assigned,
    "Diagnosis": diagnoses_assigned,
    "PHQ-9_Score": phq_9_scores,
    "Treatment": treatments_assigned,
    "CPT_Code": cpt_codes_assigned
})


data.to_csv("synthetic_health_data.csv", index=False,encoding='utf-8')

data.head(5)

